server:
  port: 9411
spring:
  application:
    name: service-zipkin

management:
  metrics:
    web:
      server:
        auto-time-requests: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

