server:
  port: 9411
spring:
  application:
    name: service-zipkin

# 关闭自动配置启用所有请求得检测
management:
  metrics:
    web:
      server:
        auto-time-requests: false  # 避免访问 zipkin 页面报 java.lang.IllegalArgumentException
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

